name: Docker Image CI

# Start the job when a new version is published
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout the code base
      - name: Checkout code
        uses: actions/checkout@v2
      # Build and push the image to DockerHub
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: stackrox/kube-linter
          tag_with_ref: true